FROM alpine:3.8

VOLUME /vol1
WORKDIR /vol1/

RUN set -ex && \
    apk add --no-cache gcc musl-dev

RUN set -ex && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/cc1obj && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto1 && \
    rm -f /usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/lto-wrapper && \
    rm -f /usr/bin/x86_64-alpine-linux-musl-gcj

COPY ./IRIS/ /vol1/



CMD gcc -c example4.c && \
    gcc -c genann.c && \
    gcc -o example4 example4.o genann.o -lm && \
    ./example4
