FROM alpine:3.8

VOLUME /vol1/
WORKDIR /vol1/

COPY src/ /vol1/src/
COPY Model/ /vol1/Model/
COPY Makefile /vol1/

RUN set -ex && \
    apk add --no-cache gcc musl-dev make && \
    make
#cest ici quil faut ajouter les commandes necessaires a lexecution du programme

CMD /vol1/bin/demo_server "./Model/ModeleCNN.txt"
