FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY server.py server.py
COPY templates templates


CMD ["python", "server.py"]