FROM alpine:3.8

VOLUME /vol1/
WORKDIR /vol1/

RUN set -ex && \
    apk add --no-cache gcc musl-dev

COPY src/ /vol1/

#cest ici quil faut ajouter les commandes necessaires a lexecution du programme

CMD gcc -c main.c && \
    gcc -c genann.c && \
    gcc -o main main.o genann.o -lm && \
    ./main "out/out.txt"
